// <auto-generated />
namespace TRiZHub.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20190822_AddedIsDeletedToClients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190822_AddedIsDeletedToClients));
        
        string IMigrationMetadata.Id
        {
            get { return "201908220943584_2019-08-22_AddedIsDeletedToClients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
