// <auto-generated />
namespace TRiZHub.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20190822_AddedIsDeletedToProjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190822_AddedIsDeletedToProjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201908220826178_2019-08-22_AddedIsDeletedToProjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
